# Generated by Django 6.0 on 2025-12-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo_practice', '0002_car_owner_dealerprofile_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_type', models.CharField(choices=[('threading', 'Threading'), ('multiprocessing', 'Multiprocessing')], max_length=20)),
                ('num_workers', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('num_queries', models.IntegerField(default=100)),
                ('execution_time', models.FloatField()),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'benchmark_results',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
    ]
